---
name: "Template"
guid: "70dd8311-1053-4eb7-8406-8df766b2d040"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.SmartCollections.dll"
changelog: >
  changelog
